In [15]:
import os
import re
import unicodedata
import glob
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from stop_words_custom import stop_word_list
from unpack_documents import load_documents, preprocess, CustomPorterStemmer

# Directory containing .txt files
TEXT_DIR = "text" 

# Directory containing other metadata
DATA_DIR = "data"

In [2]:
male_pronouns = ["he", "him"]
female_pronouns = ["she", "her"]

## Load documents

In [3]:
filepaths = glob.glob(os.path.join(TEXT_DIR, "*.txt"))

corpus, filenames, titles = load_documents(filepaths)

Loaded 762 documents

## Preprocessing documents (stemming)

In [4]:
stemmer = CustomPorterStemmer()

corpus_stemmed = [preprocess(doc, stemmer) for doc in corpus]

## Bag of words

In [5]:
vectorizer = CountVectorizer(
    strip_accents='unicode',
    stop_words=stop_word_list,
    max_df=1.0,
    min_df=5
)

X = vectorizer.fit_transform(corpus_stemmed)

print("Matrix shape:", X.shape)

/Users/mjl09005/Library/CloudStorage/OneDrive-UniversityofConnecticut/gvp/docx_env/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['articl', 'mon'] not in stop_words.
  warnings.warn(

Matrix shape: (762, 14355)

In [6]:
feature_names = vectorizer.get_feature_names_out()

bow_df = pd.DataFrame(X.toarray(), columns=feature_names, index=titles)

bow_df.head()

,aa,aaron,aback,abalon,abandon,abash,abat,abattoir,abbey,abbi,...,zigzag,zillion,zinc,zip,zipper,zombi,zone,zoo,zoom,zu
Brisk Money,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Specimen 313,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
When We Were Heroes,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Tie A Yellow Ribbon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Apologue,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [7]:
word_counts = bow_df.sum(axis=0).sort_values(ascending=False)

word_counts.head()

he      70200
him     69431
she     59722
her     58112
they    29427
dtype: int64

In [8]:
sum_male = 0
sum_female = 0

for pronoun in male_pronouns:
    sum_male += word_counts.get(pronoun, 0)

for pronoun in female_pronouns:
    sum_female += word_counts.get(pronoun, 0)

print(f"Total male pronouns: {sum_male}")
print(f"Total female pronouns: {sum_female}")

Total male pronouns: 139631
Total female pronouns: 117834

In [9]:
bow_df["male_total"] = bow_df[male_pronouns].sum(axis=1)
bow_df["female_total"] = bow_df[female_pronouns].sum(axis=1)

In [32]:
stats = pd.read_csv('data/compiled_stats.csv')

In [33]:
stats['cleaned_title'] = (
       stats['Title']
       #.apply(lambda x: unicodedata.normalize('NFKD', x).encode('ascii', 'ignore').#decode('ascii')
       #          if isinstance(x, str) else x)
       .str.replace(r"[:#/]", "", regex=True)
)

In [34]:
pronoun_data = (
    stats[stats['Type']=="Original Fiction"].merge(
        bow_df[['male_total', 'female_total']],
        left_on='cleaned_title',
        right_index=True,
        how='left'
    )
)

In [35]:
pronoun_data.head()

,Publication Date,Publication Year,Title,Author,Pronoun,Edited by,Edited by 2,Series,Type,Category,Subcategory,Subsubcategory,Word Count,Page Count,cleaned_title,male_total,female_total
1,20-Jul-08,2008,Down on the Farm,Charles Stross,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Fantasy,Lovecraftian,NaN,12682.0,NaN,Down on the Farm,159.0,113.0
2,20-Jul-08,2008,After the Coup,John Scalzi,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Science Fiction,Space Opera,NaN,7087.0,NaN,After the Coup,237.0,12.0
4,6-Aug-08,2008,The Things That Make Me Weak and Strange Get E...,Cory Doctorow,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,NaN,NaN,NaN,15708.0,NaN,The Things That Make Me Weak and Strange Get E...,805.0,137.0
5,26-Aug-08,2008,Shade,Steven Gould,He/him,NaN,NaN,NaN,Original Fiction,NaN,NaN,NaN,5619.0,NaN,Shade,251.0,104.0
6,11-Sep-08,2008,The Girl Who Sang Rose Madder,Elizabeth Bear,She/her,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Fantasy,NaN,NaN,5706.0,NaN,The Girl Who Sang Rose Madder,123.0,315.0

In [36]:
num_nans = pronoun_data['female_total'].isna().sum()
print(num_nans)

49

In [37]:
pronoun_data[pronoun_data['female_total'].isna()]

,Publication Date,Publication Year,Title,Author,Pronoun,Edited by,Edited by 2,Series,Type,Category,Subcategory,Subsubcategory,Word Count,Page Count,cleaned_title,male_total,female_total
52,4-Dec-09,2009,I Speak Fluent Giraffe,Jason Henninger,He/him,NaN,NaN,NaN,Original Fiction,Humor,NaN,NaN,0.0,NaN,I Speak Fluent Giraffe,NaN,NaN
71,21-Apr-10,2010,"Four Horsemen, at Their Leisure",Richard Parks,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Apocalyptic and Post-Apocalyptic,Fantasy,NaN,3648.0,NaN,"Four Horsemen, at Their Leisure",NaN,NaN
83,12-Jul-10,2010,The President's Brain Is Missing,John Scalzi,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Humor,Science Fiction,NaN,6695.0,NaN,The President's Brain Is Missing,NaN,NaN
121,21-Dec-10,2010,The Trains that Climb the Winter Tree,Michael Swanwick,He/him,NaN,NaN,NaN,Original Fiction,Fantasy,NaN,NaN,11556.0,NaN,The Trains that Climb the Winter Tree,NaN,NaN
122,21-Dec-10,2010,The Trains that Climb the Winter Tree,Eileen Gunn,She/her,NaN,NaN,NaN,Original Fiction,Fantasy,NaN,NaN,11556.0,NaN,The Trains that Climb the Winter Tree,NaN,NaN
130,1-Apr-11,2011,"The Shadow War of the Night Dragons, Book One:...",John Scalzi,He/him,NaN,NaN,NaN,Original Fiction,Book Excerpt,NaN,NaN,3741.0,NaN,"The Shadow War of the Night Dragons, Book One ...",NaN,NaN
226,6-Jun-12,2012,The Witch of Duva: A Ravkan Folk Tale,Leigh Bardugo,She/her,Noa Wheeler,NaN,NaN,Original Fiction,Fantasy,Young Adult,NaN,7834.0,NaN,The Witch of Duva A Ravkan Folk Tale,NaN,NaN
276,12-Mar-13,2013,Border Dogs: A SEAL Team 666 Adventure,Weston Ochse,He/him,Brendan Deneen,NaN,NaN,Original Fiction,Fantasy,Urban Fantasy,NaN,11735.0,NaN,Border Dogs A SEAL Team 666 Adventure,NaN,NaN
342,8-Oct-13,2013,Slayers: The Making of a Mentor,C. J. Hill,She/her,Lauren Burniac,NaN,NaN,Original Fiction,Fantasy,Young Adult,NaN,16910.0,NaN,Slayers The Making of a Mentor,NaN,NaN
377,26-Mar-14,2014,Anyway: Angie,Daniel José Older,He/him,Carl Engle-Laird,NaN,NaN,Original Fiction,Horror,Urban Fantasy,NaN,6950.0,NaN,Anyway Angie,NaN,NaN
389,13-May-14,2014,Unlocked: An Oral History of Hayden's Syndrome,John Scalzi,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Science Fiction,Technothriller,NaN,21662.0,NaN,Unlocked An Oral History of Hayden's Syndrome,NaN,NaN
417,12-Aug-14,2014,Sleeper,Jo Walton,She/her,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Dystopian,Science Fiction,NaN,3743.0,NaN,Sleeper,NaN,NaN
435,15-Oct-14,2014,Nuestra Señora de la Esperanza,Carrie Vaughn,She/her,George R. R. Martin,NaN,Wild Cards on Tor.com,Original Fiction,Fantasy,Urban Fantasy,NaN,9649.0,NaN,Nuestra Señora de la Esperanza,NaN,NaN
444,9-Dec-14,2014,Father Christmas: A Wonder Tale of the North,Charles Vess,He/him,NaN,NaN,NaN,Original Fiction,NaN,NaN,NaN,9461.0,NaN,Father Christmas A Wonder Tale of the North,NaN,NaN
458,18-Feb-15,2015,Schrödinger's Gun,Ray Wood,He/him,Carl Engle-Laird,NaN,NaN,Original Fiction,Alternate History,Science Fiction,NaN,7679.0,NaN,Schrödinger's Gun,NaN,NaN
473,29-Apr-15,2015,Ambiguity Machines: An Examination,Vandana Singh,She/her,Ann VanderMeer,NaN,NaN,Original Fiction,NaN,NaN,NaN,7872.0,NaN,Ambiguity Machines An Examination,NaN,NaN
489,22-Jul-15,2015,The Totally Secret Origin of Foxman: Excerpts ...,Kelly McCullough,He/him,Holly West,NaN,NaN,Original Fiction,Science Fiction,Young Adult,NaN,7812.0,NaN,The Totally Secret Origin of Foxman Excerpts f...,NaN,NaN
540,27-Apr-16,2016,La beauté sans vertu,Genevieve Valentine,She/her,Ellen Datlow,NaN,NaN,Original Fiction,Science Fiction,NaN,NaN,4339.0,NaN,La beauté sans vertu,NaN,NaN
577,1-Nov-16,2016,Dune: Red Plague,Brian Herbert,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Science Fiction,Space Opera,NaN,3952.0,NaN,Dune Red Plague,NaN,NaN
578,1-Nov-16,2016,Dune: Red Plague,Kevin J Anderson,He/him,Patrick Nielsen Hayden,NaN,NaN,Original Fiction,Science Fiction,Space Opera,NaN,3952.0,NaN,Dune Red Plague,NaN,NaN
589,11-Jan-17,2017,Microbiota and the Masses: A Love Story,S. B. Divya,She/her,Carl Engle-Laird,NaN,NaN,Original Fiction,Romantic,Science Fiction,NaN,7162.0,NaN,Microbiota and the Masses A Love Story,NaN,NaN
686,3-Apr-19,2019,One/Zero,Kathleen Ann Goonan,She/her,Ellen Datlow,NaN,NaN,Original Fiction,Science Fiction,NaN,NaN,10251.0,NaN,OneZero,NaN,NaN
705,9-Oct-19,2019,Water: A History,KJ Kabza,He/him,Ruoxi Chen,NaN,NaN,Original Fiction,NaN,NaN,NaN,3452.0,NaN,Water A History,NaN,NaN
719,15-Jan-20,2020,How Quini the Squid Misplaced His Klobučar,Rich Larson,He/him,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,11417.0,NaN,How Quini the Squid Misplaced His Klobučar,NaN,NaN
725,26-Feb-20,2020,Sinew and Steel and What They Told,Carrie Vaughn,She/her,Ann VanderMeer,NaN,NaN,Original Fiction,NaN,NaN,NaN,4426.0,NaN,Sinew and Steel and What They Told,NaN,NaN
728,18-Mar-20,2020,The Visitor: Kill or Cure,Mark Lawrence,He/him,George R. R. Martin,NaN,Wild Cards on Tor.com,Original Fiction,NaN,NaN,NaN,10283.0,NaN,The Visitor Kill or Cure,NaN,NaN
755,23-Sep-20,2020,The Perfection of Theresa Watkins,Justin C. Key,He/him,Diana Pho,NaN,NaN,Original Fiction,NaN,NaN,NaN,12695.0,NaN,The Perfection of Theresa Watkins,NaN,NaN
766,21-Oct-20,2020,City of Red Midnight: A Hikayat,Usman T. Malik,He/him,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,14051.0,NaN,City of Red Midnight A Hikayat,NaN,NaN
777,2/10/21,2021,Judge Dee and the Three Deaths of Count Werden...,Lavie Tidhar,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,8855.0,NaN,Judge Dee and the Three Deaths of Count Werden...,NaN,NaN
779,3/3/21,2021,"#Spring Love, #Pichal Pairi",Usman T. Malik,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,7419.0,NaN,"Spring Love, Pichal Pairi",NaN,NaN
782,4/7/21,2021,Annie Without Crow,Michael Swanwick,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,5569.0,NaN,Annie Without Crow,NaN,NaN
785,5/5/21,2021,The Lay of Lilyfinger,G. V. Anderson,She/her,Emily Goldman,NaN,NaN,Original Fiction,NaN,NaN,NaN,10117.0,NaN,The Lay of Lilyfinger,NaN,NaN
788,6/9/21,2021,An Easy Job,Carrie Vaughn,She/her,Ann VanderMeer,NaN,NaN,Original Fiction,NaN,NaN,NaN,7364.0,NaN,An Easy Job,NaN,NaN
789,6/16/21,2021,The Far Side of the Universe,noc,They/them,"Ruoxi Chen, Lindsey Hall",NaN,NaN,Original Fiction,NaN,NaN,NaN,1809.0,NaN,The Far Side of the Universe,NaN,NaN
790,6/23/21,2021,The Red Mother,Elizabeth Bear,She/her,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,12071.0,NaN,The Red Mother,NaN,NaN
794,8/4/21,2021,Aptitude,Cooper Shrivastava,She/her,Ann VanderMeer,NaN,NaN,Original Fiction,NaN,NaN,NaN,8022.0,NaN,Aptitude,NaN,NaN
796,8/25/21,2021,L'Esprit de L'Escalier,Catherynne M. Valente,She/her,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,9346.0,NaN,L'Esprit de L'Escalier,NaN,NaN
797,9/1/21,2021,"The Wonderful Stag, or The Courtship of Red Elsie",Kathleen Jennings,She/her,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,1904.0,NaN,"The Wonderful Stag, or The Courtship of Red Elsie",NaN,NaN
798,9/8/21,2021,The Station of the Twelfth,Chaz Brenchley,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,2881.0,NaN,The Station of the Twelfth,NaN,NaN
812,2/16/22,2022,Seven Vampires: A Judge Dee Mystery,Lavie Tidhar,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,9549.0,NaN,Seven Vampires A Judge Dee Mystery,NaN,NaN
815,4/6/22,2022,Sword & Spore,Dominica Phetteplace,NaN,Ann VanderMeer,NaN,NaN,Original Fiction,NaN,NaN,NaN,12311.0,NaN,Sword & Spore,NaN,NaN
817,4/20/22,2022,"Men, Women, and Chainsaws",Stephen Graham Jones,NaN,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,7877.0,NaN,"Men, Women, and Chainsaws",NaN,NaN
823,7/13/22,2022,The Sisters of Saint Nicola of the Almost Perp...,Garth Nix,He/him,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,7930.0,NaN,The Sisters of Saint Nicola of the Almost Perp...,NaN,NaN
827,8/10/22,2022,Porgee's Boar,Jonathan Carroll,He/him,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,5800.0,NaN,Porgee's Boar,NaN,NaN
828,8/24/22,2022,D.I.Y.,John Wiswell,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,4883.0,NaN,D.I.Y.,NaN,NaN
841,2/8/23,2023,Even If Such Ways Are Bad,Rich Larson,He/him,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,8400.0,NaN,Even If Such Ways Are Bad,NaN,NaN
859,8/23/23,2023,The Three O'Clock Dragon,John Wiswell,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,4615.0,NaN,The Three O'Clock Dragon,NaN,NaN
864,10/4/23,2023,Jack O'Dander,Priya Sharma,She/her,Ellen Datlow,NaN,NaN,Original Fiction,NaN,NaN,NaN,7641.0,NaN,Jack O'Dander,NaN,NaN
866,10/25/23,2023,The Locked Coffin: A Judge Dee Mystery,Lavie Tidhar,He/him,Jonathan Strahan,NaN,NaN,Original Fiction,NaN,NaN,NaN,7624.0,NaN,The Locked Coffin A Judge Dee Mystery,NaN,NaN